<?php echo $this->doctype(); ?>

<html lang="en" id="extr-page">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('sclogic '. $this->translate('School Logic'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/login/style.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/login/smartadmin-production-plugins.min.css')
                        ->prependStylesheet($this->basePath() . '/css/login/smartadmin-production.min.css')
                        ->prependStylesheet($this->basePath() . '/css/login/smartadmin-skins.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/login/smartadmin-rtl.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/demo.min.css')?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <body class="animated fadeInDown">

        <header id="header">

            <div id="logo-group">
                <a id="logo" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/mb.png') ?>" alt="Zend Framework 2"/></a><div class="hidden-mobile hiddex-xs ltitle"><?php echo $this->translate('MIBS INTERNATIONAL ACADEMY') ?></div>
            </div>

            <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs txt-color-white">Need an account?</span> <a href="" class="btn btn-danger">Create account</a> </span>

        </header>
         
        <div id="main" role="main">

            <!-- MAIN CONTENT -->
            <div id="content" class="container">
                <div class="row">
                    
                   <?php echo $this->content; ?>
            </div>
            
        </div>
        </div> <!-- /container -->
        <div class="page-footer">
            <div class="row">
                <div class="col-xs-12 col-sm-12">
                    <span class="txt-color-white">Mibs Academy <span class="hidden-xs"> - All Rights Reserved</span> © 2014-2015</span>
                </div>
            </div>
        </div>
                 
        <?php echo $this->inlineScript()
        
            
          
            ->prependFile($this->basePath() . '/js/query.min.js')
          
            
            ->prependFile($this->basePath() . '/js/app.min.js')
            ->prependFile($this->basePath() . '/js/plugin/masked-input/jquery.maskedinput.min.js')

            ->prependFile($this->basePath() . '/js/plugin/jquery-validate/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/plugin/pace/pace.min.js')
              ->prependFile($this->basePath() . '/js/bootstrap.min.js')
              ->prependFile($this->basePath() . '/js/app.config.js')
              ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
              ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
            
            
        ; ?>
    
    </body>
   
</html>
