<!-- h1>I am in AuthDoctrine IndexController login action index.phtml</h1 -->
<?php echo $this->messages; ?>
<?php  $this->headScript()
            ->appendFile($this->basePath() . '/js/jqueryUI/ui/jquery-ui-1.8.24.custom.js')
            ->appendFile($this->basePath() . '/js/ajaxform.js')
            ->appendFile($this->basePath() . '/js/jquery-2.1.1.min.js')
            ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
            ->appendFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/plugin/pace/pace.min.js')
            ->appendFile($this->basePath() . '/js/app.min.js')
            ->appendFile($this->basePath() . '/js/plugin/masked-input/jquery.maskedinput.min.js')
            ->appendFile($this->basePath() . '/js/plugin/jquery-validate/jquery.validate.min.js'); ?>
<?php
$form = $this->form;
/**
*Set form fields classes and placeholders
*/
$form->setAttributes(array(
	'class'=>'smart-form client-form',
	)
	
);

$form->get('username')->setOptions(array(
	'class'=>'label',));

$form->get('password')->setOptions(array(
	'class'=>'label',));

$form->setAttribute('action', $this->url('login/default', array('controller' => 'user', 'action' => 'auth')));
$form->prepare();

// echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('username'));
//echo $this->formRow($form->get('password'));
//echo $this->formRow($form->get('rememberme'));
//echo $this->formSubmit($form->get('submit'));

?>
<div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
                        
                        

                            
                            
                            <img src="<?php echo $this->basePath('img/login.jpg') ?>" class="" alt="" style="width:610px">

                        

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <h5 class="about-heading">About Rubicon - Are you up to date?</h5>
                                <p>
                                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
                                </p>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <h5 class="about-heading">Not just your average afdsf!</h5>
                                <p>
                                    Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
                                </p>
                            </div>
                        </div>

                    </div>
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
						<div class="well no-padding">

							
								<?php echo $this->form()->openTag($form);?>

								<header>
									Sign In
								</header>

								<fieldset>
									
									<section>
										
										<label class="label">E-mail</label>
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($form->get('username'))."\n";?></br>
                                            <?php echo $this->formElementErrors($form->get('username'))."\n";?>
											<b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter email address/username</b></label>
											<?php echo $this->messages; ?>
									</section>

									<section>
										<label class="label">Password</label>
										<label class="input"> <i class="icon-append fa fa-lock"></i>
											<?php echo $this->formInput($form->get('password'))."\n";?></br>
                                            <?php echo $this->formElementErrors($form->get('password'))."\n";?>
											<b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b> </label>
										<div class="note">
											<a href="forgotpassword.html">Forgot password?</a>
										</div>
									</section>

									<section>
										<label class="checkbox">
											<?php echo $this->formInput($form->get('rememberme'))."\n";?>
											<i></i>Stay signed in</label>
											
									</section>
								</fieldset>
								<footer>
									<?php echo $this->formInput($form->get('submit'))."\n";?>
										
								</footer>
							<?php echo $this->form()->closeTag();?>
						</div>

		
															

<script type="text/javascript">
            runAllForms();

            $(function() {
                // Validation
                $("#login-form").validate({
                    // Rules for form validation
                    rules : {
                        email : {
                            required : true,
                            email : true
                        },
                        password : {
                            required : true,
                            minlength : 3,
                            maxlength : 20
                        }
                    },

                    // Messages for form validation
                    messages : {
                        email : {
                            required : 'Please enter your email address',
                            email : 'Please enter a VALID email address'
                        },
                        password : {
                            required : 'Please enter your password'
                        }
                    },

                    // Do not change code below
                    errorPlacement : function(error, element) {
                        error.insertAfter(element.parent());
                    }
                });
            });
        </script>
	


