
					<?php $form = $this->form;
				$form->setAttribute('action', $this->url('admin/default',array('action'=> 'add','controller' => 'section')));
											$form->prepare(); ?>

											<?php echo $this->form()->openTag($form); ?>
							<div class="col md-5"	
								<div class="row">
									<section class="col col-6">
										<label class="label">Section Name</label>
										<label class="select">
									 <?php echo $this->formInput($form->get('name')); ?>
									 	<i></i></label>
									</section>

									<section class="col col-6">
										<label class="label">Description</label>
										<label class="select">
										 <?php echo $this->formInput($form->get('description')); ?>
										 <i></i></label>
									</section>
								</div>
								<div class="row">							
										
									<?php echo $this->formRow($form->get('submit')); ?>
								
								<?php echo $this->form()->closeTag(); ?>
								</div>
							</div>

							<div class="col md-7">
							<?php echo $this->widgetContent ?>	
								
							</div>