
        <?php echo $this->headScript()
            
            ->appendFile($this->basePath() . '/js/jquery-2.1.1.min.js')
            ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
            ->appendFile($this->basePath() . '/js/app.config.js')
            ->appendFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/plugin/pace/pace.min.js')
            ->appendFile($this->basePath() . '/js/app.min.js')
            ->appendFile($this->basePath() . '/js/demo.min.js')
            ->prependFile($this->basePath() . '/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js')
            ->appendFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->appendFile($this->basePath() . '/js/plugin/select2/select2.min.js')
           ->appendFile($this->basePath() . '/js/ajaxform.js')
           ->appendFile($this->basePath() . '/js/edit.js')
           ->appendFile($this->basePath() . '/js/editterm.js')
             //  $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'text/javascript')
              //      ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                //    ->appendFile('/jqGrid/js/i18n/grid.locale-en.js', 'text/javascript')
                //    ->appendFile('/jqGrid/plugins/ui.multiselect.js', 'text/javascript')
                //    ->appendFile('/jqGrid/js/jquery.jqGrid.min.js', 'text/javascript') 
        ; ?>

<article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<div class="jarviswidget jarviswidget-color-Darken" id="wid-id-18" data-widget-colorbutton="false" data-widget-editbutton="false">
        <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
        data-widget-colorbutton="false" 
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true" 
        data-widget-sortable="false"   
                                -->
             <header>
                <h2><strong>MANAGE SECTION</strong></h2>               
             </header>
                <!-- widget div-->
    <div>       
       <!-- widget edit box -->
         <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
            <input class="form-control" type="text">
            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>      
          </div>
                <!-- end widget edit box -->
                <!-- widget content -->
            <div class="widget-body no-padding">
                <div class="widget-body-toolbar"> 
                    
                    <div class="row alert alert-info no-margin fade in"> 
                        
                        <?php $formsection = $this->formsection;
                        $formsection->setAttribute('action', $this->url('admin/default',array('action'=> 'addsection','controller' => 'section')));
                        $formsection->prepare(); ?>
                        <?php echo $this->form()->openTag($formsection); ?>
                
                                       
                        <div class="row"> 
                        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                            <?php echo $this->formElementErrors($formsection->get('name')); ?>
                            <?php echo $this->formInput($formsection->get('name')); ?>    
                        </div>

                        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                        <?php echo $this->formElementErrors($formsection->get('description')); ?>
                        <?php echo $this->formInput($formsection->get('description')); ?>      
                         <?php echo $this->formRow($formsection->get('submit')); ?>
                        </div>
                        </div>
                        
                        <div class="row">
                        <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">             
                        </div>
                        </div>
                              <?php echo $this->form()->closeTag(); ?>
                    </div>
                
                </div>
                                        
                <div class="custom-scroll table-responsive" style="height:290px; overflow-y: scroll;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</i></th>
                                <th>Action</th>
                            </tr>
                        </thead><?php foreach ($sections as $section) : ?>
                        <tbody>
                            <tr>
                    <td><?php echo $this->escapeHtml($section->getName());?></td>
                    <td><?php echo $this->escapeHtml($section->getDescription());?></td>
                    <td>
<a id="editterm" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'editsection', 'id' => $section->getid()));?>"><button class="btn btn-xs btn-default"><i class='fa fa-pencil'></i></button></a>

<a id="conf" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'deletesection', 'id' => $section->getid()));?>"onclick="return confirm('Do you rely want to delete this section?')"><button class="btn btn-xs btn-default"><i class='fa fa-times'></i></button></a>
                    </td>                                                        
                        </tr><?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
        
          </div>
                                    <!-- end widget content --> 
        </div>
        <!-- end widget div -->   
    </div>
    <!-- end widget -->
</article>

<article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-18" data-widget-colorbutton="false" data-widget-editbutton="false">
        <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
        data-widget-colorbutton="false" 
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true" 
        data-widget-sortable="false"   
                                -->
             <header>
                <h2><strong>MANAGE CLASSES</strong></h2>               
             </header>
                <!-- widget div-->
    <div>       
       <!-- widget edit box -->
         <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
            <input class="form-control" type="text">
            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>      
          </div>
                <!-- end widget edit box -->
                <!-- widget content -->
            <div class="widget-body no-padding">
                <div class="widget-body-toolbar"> 
                    
                    <div class="row alert alert-info no-margin fade in">    
                         <?php $formclasses = $this->formclasses;
                        $formclasses->setAttribute('action', $this->url('admin/default',array('action'=> 'addclasses','controller' => 'section')));
                        $formclasses->prepare(); ?>
                        <?php echo $this->form()->openTag($formclasses); ?>
                
                                       
                        <div class="row"> 
                        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                            <?php echo $this->formElementErrors($formclasses->get('name')); ?>
                            <?php echo $this->formInput($formclasses->get('name')); ?>    
                        </div>

                        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                        <?php echo $this->formElementErrors($formclasses->get('section')); ?>
                        <?php echo $this->formSelect($formclasses->get('section')); ?>      
                         <?php echo $this->formRow($formclasses->get('submit')); ?>
                        </div>
                        </div>
                        
                        <div class="row">
                        <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">             
                        </div>
                        </div>
                              <?php echo $this->form()->closeTag(); ?>
                    </div>
                
                </div>
                                        
                <div class="custom-scroll table-responsive" style="height:290px; overflow-y: scroll;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Section</i></th>
                                <th>Action</th>
                            </tr>
                        </thead><?php foreach ($classes as $class) : ?>
                        <tbody>
                            <tr>
                    <td><?php echo $this->escapeHtml($class->getName());?></td>
                    <td><?php echo $this->escapeHtml($class->getSection()->getName());?></td>
                    <td>
<a id="editterm" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'editclasses', 'id' => $class->getid()));?>"><button class="btn btn-xs btn-default"><i class='fa fa-pencil'></i></button></a>

<a id="conf" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'deleteclasses', 'id' => $class->getid()));?>"onclick="return confirm('Do you rely want to delete this class?')"><button class="btn btn-xs btn-default"><i class='fa fa-times'></i></button></a>
                    </td>                                                        
                        </tr><?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
        
          </div>
                                    <!-- end widget content --> 
        </div>
        <!-- end widget div -->   
    </div>
    <!-- end widget -->
</article>






 </article>
                        <!-- WIDGET END -->




<script type="text/javascript">
        
        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        
        $(document).ready(function() {
            
            pageSetUp();
            // START AND FINISH DATE
            $('#startdate').datepicker({
                dateFormat : 'dd.mm.yy',
                prevText : '<i class="fa fa-chevron-left"></i>',
                nextText : '<i class="fa fa-chevron-right"></i>',
                onSelect : function(selectedDate) {
                    $('#enddate').datepicker('option', 'minDate', selectedDate);
                }
            });
            
            $('#enddate').datepicker({
                dateFormat : 'dd.mm.yy',
                prevText : '<i class="fa fa-chevron-left"></i>',
                nextText : '<i class="fa fa-chevron-right"></i>',
                onSelect : function(selectedDate) {
                    $('#startdate').datepicker('option', 'maxDate', selectedDate);
                }
            });
            

            $("#conf").click(function(e) {
                $.SmartMessageBox({
                    title : "Smart Alert!",
                    content : "This is a confirmation box. Can be programmed for button callback",
                    buttons : '[No][Yes]'
                }, function(ButtonPressed) {
                    if (ButtonPressed === "Yes") {
        
                        $.smallBox({
                            title : "Callback function",
                            content : "<i class='fa fa-clock-o'></i> <i>You pressed Yes...</i>",
                            color : "#659265",
                            iconSmall : "fa fa-check fa-2x fadeInRight animated",
                            timeout : 4000
                        });
                    }
                    if (ButtonPressed === "No") {
                        $.smallBox({
                            title : "Callback function",
                            content : "<i class='fa fa-clock-o'></i> <i>You pressed No...</i>",
                            color : "#C46A69",
                            iconSmall : "fa fa-times fa-2x fadeInRight animated",
                            timeout : 4000
                        });
                    }
        
                });
                e.preventDefault();
            })
            /* // DOM Position key index //
        
            l - Length changing (dropdown)
            f - Filtering input (search)
            t - The Table! (datatable)
            i - Information (records)
            p - Pagination (paging)
            r - pRocessing 
            < and > - div elements
            <"#id" and > - div with an id
            <"class" and > - div with a class
            <"#id.class" and > - div with an id and class
            
            Also see: http://legacy.datatables.net/usage/features
            */  
    
            /* BASIC ;*/
                var responsiveHelper_dt_basic = undefined;
                var responsiveHelper_datatable_fixed_column = undefined;
                var responsiveHelper_datatable_col_reorder = undefined;
                var responsiveHelper_datatable_tabletools = undefined;
                
                var breakpointDefinition = {
                    tablet : 1024,
                    phone : 480
                };
    
                $('#dt_basic').dataTable({
                    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
                        "t"+
                        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                    "autoWidth" : true,
                    "preDrawCallback" : function() {
                        // Initialize the responsive datatables helper once.
                        if (!responsiveHelper_dt_basic) {
                            responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                        }
                    },
                    "rowCallback" : function(nRow) {
                        responsiveHelper_dt_basic.createExpandIcon(nRow);
                    },
                    "drawCallback" : function(oSettings) {
                        responsiveHelper_dt_basic.respond();
                    }
                });
    
            /* END BASIC */
            
            /* COLUMN FILTER  */
            var otable = $('#datatable_fixed_column').DataTable({
                //"bFilter": false,
                //"bInfo": false,
                //"bLengthChange": false
                //"bAutoWidth": false,
                //"bPaginate": false,
                //"bStateSave": true // saves sort state using localStorage
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>"+
                        "t"+
                        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth" : true,
                "preDrawCallback" : function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_datatable_fixed_column) {
                        responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
                    }
                },
                "rowCallback" : function(nRow) {
                    responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
                },
                "drawCallback" : function(oSettings) {
                    responsiveHelper_datatable_fixed_column.respond();
                }       
            
            });
            
            // custom toolbar
            $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');
                   
            // Apply the filter
            $("#datatable_fixed_column thead th input[type=text]").on( 'keyup change', function () {
                
                otable
                    .column( $(this).parent().index()+':visible' )
                    .search( this.value )
                    .draw();
                    
            } );
            /* END COLUMN FILTER */   
        
            /* COLUMN SHOW - HIDE */
            $('#datatable_col_reorder').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>"+
                        "t"+
                        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                "autoWidth" : true,
                "preDrawCallback" : function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_datatable_col_reorder) {
                        responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
                    }
                },
                "rowCallback" : function(nRow) {
                    responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
                },
                "drawCallback" : function(oSettings) {
                    responsiveHelper_datatable_col_reorder.respond();
                }           
            });
            
            /* END COLUMN SHOW - HIDE */
            $(document).ready(function(){
             $('#dt_basic').DataTable();
            });
    
            /* TABLETOOLS */
            $('#datatable_tabletools').dataTable({
                
                // Tabletools options: 
                //   https://datatables.net/extensions/tabletools/button_options
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
                        "t"+
                        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                "oTableTools": {
                     "aButtons": [
                     "copy",
                     "csv",
                     "xls",
                        {
                            "sExtends": "pdf",
                            "sTitle": "SmartAdmin_PDF",
                            "sPdfMessage": "SmartAdmin PDF Export",
                            "sPdfSize": "letter"
                        },
                        {
                            "sExtends": "print",
                            "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                        }
                     ],
                    "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
                },
                "autoWidth" : true,
                "preDrawCallback" : function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_datatable_tabletools) {
                        responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
                    }
                },
                "rowCallback" : function(nRow) {
                    responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
                },
                "drawCallback" : function(oSettings) {
                    responsiveHelper_datatable_tabletools.respond();
                }
            });
            
            /* END TABLETOOLS */
        
        })

        </script>
