<h1>I am in AuthDoctrine IndexController index action index.phtml</h1>

<?php echo $this->message; ?>

<?php var_dump($this->users); ?>

<?php 
echo '<pre>';
print_r($this->users); 
echo '</pre>';
?>
<hr />
<table>
	<tr>
		<th>UserName</th>
		<th>Password</th>
		<th>Email</th>
		<th>Role</th>
		<th>Languag</th>
	</tr>
<?php foreach ($users as $user) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($user->getUsrName());?></td>
		<td><?php echo $this->escapeHtml($user->getUsrPassword());?></td>
		<td><?php echo $this->escapeHtml($user->getUsrEmail());?></td>
		<td><?php echo $this->escapeHtml($user->getUsrlId());?></td>
		<td><?php echo $this->escapeHtml($user->getLngId());?></td>
	</tr>
<?php } ?>
</table>