
 <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 hidden-xs hidden-sm">
                        
                        

                            
                            
                            <img src="<?php echo $this->basePath('img/login.jpg') ?>" class="" alt="" style="width:610px">
 </div>
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
						<div class="well no-padding">

							<h1><?php echo sprintf($this->translate('An e-mail has been sent to %s. Please, check your inbox and confirm your registration!'), $usr_email);?></h1>
						</div>
						
					</div>
				<!-- Modal -->
		
